Glaneir.Admin/Controllers/AccountController.cs
using Glaneir.Core.Enumerations;
using Glaneir.Core.Models;
using Glaneir.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Glaneir.Admin.Controllers
{
    public class AccountController : ApplicationBaseController
    {
        private UserService _service;

        [AllowAnonymous]
        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToActionPermanent("Index", "Home");
            return View();
        }


        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Login(AdminLoginModel model)
        {
            if (ModelState.IsValid)
            {
                _service = new UserService(Request.GetOwinContext());
                ResponseModel<object> mResult = await _service.AdminLogin(model);
                OnBindMessage(mResult.Status, mResult.Message);
                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToAction("Index", "Home");
                ModelState.AddModelError("", mResult.Message);
            }
            return View(model);
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> ChangePassword(AdminChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                _service = new UserService(Request.GetOwinContext());
                ResponseModel<object> mResult = await _service.AdminChangePassword(model);

                OnBindMessage(mResult.Status, mResult.Message);
                if (mResult.Status == ResponseStatus.Success)
                {
                    return RedirectToActionPermanent("Index", "Users");
                }
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult LogOut()
        {
            _service = new UserService(Request.GetOwinContext());
            _service.WebLogout();
            return RedirectToActionPermanent("Login", "Account");
        }


    }
}

Glaneir.Admin/Controllers/ApplicationBaseController.cs
using Glaneir.Core.Enumerations;
using Glaneir.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Glaneir.Admin.Controllers
{
    public class ApplicationBaseController : Controller
    {
        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            if (!ModelState.IsValid)
            {
                string messages = string.Join(Environment.NewLine, ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage));
                OnBindMessage(AlertStatus.danger, messages);
            }
            base.OnActionExecuted(filterContext);
        }

        public void OnBindMessage(ResponseStatus status, string message)
        {
            OnBindMessage((status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger), message);
        }
        public void OnBindMessage(AlertStatus status, string message)
        {
            TempData["alertModel"] = new AlertModel(status, message);
        }

        public void OnInitBreadcrumb()
        {
            string actionName = ControllerContext.RouteData.Values["action"].ToString();
            string controllerName = ControllerContext.RouteData.Values["controller"].ToString();

            if (controllerName != "Home")
            {
                if (actionName == "Index")
                {
                    ViewBag.breadcrumbModel = new BreadcrumbModel()
                    {
                        subActionTitle = controllerName
                    };
                }
                else
                {
                    ViewBag.Action = actionName;
                    ViewBag.breadcrumbModel = new BreadcrumbModel()
                    {
                        actioncontroller = controllerName,
                        actionName = "Index",
                        actionTitle = controllerName,
                        subActionTitle = actionName
                    };
                }
            }
        }
    }
}

Glaneir.Admin/Controllers/CardController.cs
using Glaneir.Core.Models;
using Glaneir.Service;
using System.Linq;
using System.Web.Mvc;

namespace Glaneir.Admin.Controllers
{
    public class CardController : Controller
    {
        private CardService _service;
        public CardController()
        {
            _service = new CardService();
        }

        public ActionResult ViewCardByUserId(string id)
        {
            IQueryable<CardViewModel> objCard = _service.GetUserCardList(id);
            return View(objCard);
        }
    }
}

Glaneir.Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Glaneir.Admin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Glaneir.Admin/Controllers/UsersController.cs
using Glaneir.Core.Models;
using Glaneir.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Glaneir.Admin.Controllers
{
    public class UsersController : Controller
    {
        private UserService _service;
        public UsersController()
        {
            _service = new UserService();
        }

        public ActionResult Index()
        {
            IQueryable<UserDetailsModel> objUsers = _service.getAllUsers_IQueryable();
            return View(objUsers);
        }

        [HttpPost]
        public JsonResult ActiveToggle(string Id)
        {
            ResponseModel<bool> mResult = _service.ActiveToggle(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            ResponseModel<object> mResult = await _service.Delete(id);
            //OnBindMessage(mResult.Status, mResult.Message);
            return RedirectToAction("Index");
        }

        public ActionResult ForgetPassword(string UserId)
        {
            ViewBag.userid = UserId;
            return View();
        }

        [AllowAnonymous]
        public ActionResult ResetPassword(string UserId)
        {
            ViewBag.userid = UserId;
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> SetPassword(ResetPasswordModel model)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            mResult = await _service.SetPassword(model);
            return Json(mResult.Message, JsonRequestBehavior.AllowGet);
        }
    }
}

Glaneir.Admin/Controllers/UtilityController.cs
using Glaneir.Core.Enumerations;
using Glaneir.Core.Helper;
using Glaneir.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Glaneir.Admin.Controllers
{
    public class UtilityController : ApplicationBaseController
    {
        public ActionResult About()
        {
            UtilityModel model = new UtilityModel();
            try
            {
                string FilePath = GlobalConfig.fileRoutePath + "About.html";
                model.Description = System.IO.File.ReadAllText(FilePath);
            }
            catch (Exception ex)
            {
                OnBindMessage(AlertStatus.danger, ex.Message + "InnerExceptionError" + ex.InnerException);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AboutPost(UtilityModel model)
        {
            string FilePath = GlobalConfig.fileRoutePath + "About.html";
            System.IO.File.WriteAllText(FilePath, model.Description);
            OnBindMessage(AlertStatus.success, "About Us updated successfully.");
            return RedirectToAction("About");
        }
    }
}

Glaneir.Admin/Views/Card/ViewCardByUserId.cshtml
@model IQueryable<CardViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "ViewCardByUserId";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">All Cards</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {

                               column.Add(p => p.CardName)
                               .Titled("Name On Card")
                               .Filterable(true)
                                 .Encoded(false)
                                .Sanitized(false)
                                .Sortable(true);

                               column.Add(p => p.CardNumber)
                               .Titled("Card Number")
                               .Filterable(true);

                               column.Add()
                             .Titled("Added Date")
                             .RenderValueAs(x => x.CreatedDateTimeUTC.ToString("dd/MM/yyyy"));

                           }).Selectable(false).WithPaging(10)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {

    @Scripts.Render("~/jQuery/gridMvc")
    <script type="text/javascript">
        ActiveMenu("AllUsers");
        $(".jsgrid-grid-body").css('overflow-x', 'auto');
    </script>
}

Glaneir.Admin/Views/Shared/_Breadcrumb.cshtml
@{ BreadcrumbModel breadcrumbModel = ViewBag.breadcrumbModel;
    if (breadcrumbModel != null)
    {
        <div class="content-header row">
            <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index","Home")">Home</a>
                    </li>
                    @if (!string.IsNullOrEmpty(breadcrumbModel.actionTitle))
                    {
                        <li class="breadcrumb-item">
                            <a href="@Url.Action(breadcrumbModel.actionName, breadcrumbModel.actioncontroller)">
                                @breadcrumbModel.actionTitle
                            </a>
                        </li>
                    }
                    @if (!string.IsNullOrEmpty(breadcrumbModel.subActionTitle))
                    {
                        <li class="breadcrumb-item active">
                            @breadcrumbModel.subActionTitle
                        </li>
                    }
                </ol>
            </div>
        </div>

    }
}

Glaneir.Admin/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Glaneir.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    AlertModel alertModel = TempData["alertModel"] as AlertModel;
    int status = -1;
    string message = null;
    if (alertModel != null)
    {
        status = (int)alertModel.alertStatus;
        message = alertModel.alertMessage;
    }
}

<html lang="en" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-w idth, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>@ViewBag.Title @GlobalConfig.ProjectName</title>
    <link rel="apple-touch-icon" sizes="60x60" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-60.png")">
    <link rel="apple-touch-icon" sizes="76x76" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-76.png")">
    <link rel="apple-touch-icon" sizes="120x120" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-120.png")">
    <link rel="apple-touch-icon" sizes="152x152" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-152.png")">
    <link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/Files/DefaultImages/favicon/favicon.ico")">
    <link rel="shortcut icon" type="image/png" href="@Url.Content("~/Files/DefaultImages/favicon/favicon-32.png")">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    @Styles.Render("~/css/bundles")
    @Styles.Render("~/css/menu")
    @Scripts.Render("~/jQuery/bundles")
    <script src="~/Content/Plugins/zoom/zoom.js"></script>
    <link href="~/Content/Plugins/zoom/zoom.css" rel="stylesheet" />
</head>
<body data-open="click" data-menu="vertical-menu" data-col="2-columns" class="vertical-layout vertical-menu 2-columns fixed-navbar" id="body">
    <!-- navbar-fixed-top-->
    <nav class="header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li class="nav-item mobile-menu hidden-md-up float-xs-left">
                        <a class="nav-link nav-menu-main menu-toggle hidden-xs">
                            <i class="icon-menu5 font-large-1"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","Home")" class="navbar-brand nav-link">
                            <img alt="@GlobalConfig.ProjectName" src="@Url.Content("~/Files/DefaultImages/logo.png")" class="brand-logo"
                                 data-expand="@Url.Content("~/Files/DefaultImages/logo.png")"
                                 data-collapse="@Url.Content("~/Files/DefaultImages/small-logo.png")">
                        </a>
                    </li>
                    <li class="nav-item hidden-md-up float-xs-right">
                        <a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container">
                            <i class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="navbar-container content container-fluid">
                <div id="navbar-mobile" class="collapse navbar-toggleable-sm">
                    <ul class="nav navbar-nav">
                        <li class="nav-item hidden-sm-down">
                            <a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5"></i></a>
                        </li>
                        <li class="nav-item hidden-sm-down"><a href="#" class="nav-link nav-link-expand"><i class="ficon icon-expand2"></i></a></li>
                    </ul>
                    <ul class="nav navbar-nav float-xs-right">
                        <li class="dropdown dropdown-user nav-item">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                                <span class="avatar avatar-online">
                                    <img src="@Url.Content("~/Files/DefaultImages/admin_avtar.png")" alt="avatar"><i></i>
                                </span>
                                <span class="user-name">Admin</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a href="@Url.Action("changepassword", "Account")" class="dropdown-item"><i class="icon-head"></i> change password</a>
                                <div class="dropdown-divider"></div>
                                <a href="@Url.Action("Logout","Account")" class="dropdown-item"><i class="icon-power3"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- main menu-->
    <div data-scroll-to-active="true" class="main-menu menu-fixed menu-dark menu-accordion menu-shadow">
        <div class="main-menu-content">
            <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
                <li class="nav-item" id="liHome">
                    <a href="@Url.Action("Index","Home")">
                        <i class="icon-home3"></i>
                        <span data-i18n="nav.dash.main" class="menu-title">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" id="liEmployee">
                    <a href="@Url.Action("Index", "Users")">
                        <i class="icon-user"></i>
                        <span data-i18n="nav.dash.main" class="menu-title">All Users</span>
                    </a>
                </li>
                <li class="nav-item" id="liPrivacy">
                    <a href="@Url.Action("About", "Utility")">
                        <i class="icon-security"></i>
                        <span data-i18n="nav.templates.main" class="menu-title">About Us</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <!-- / main menu-->

    <div class="app-content content container-fluid">
        <div class="content-wrapper">
            @Html.Partial("_Breadcrumb")
            <div class="content-body">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="footer footer-static footer-light navbar-border">
        <p class="clearfix text-muted text-sm-center mb-0 px-2">
            <span class="float-md-left d-xs-block d-md-inline-block">
                Copyright  &copy; @DateTime.Now.Year
                <a href="#" target="_blank" class="text-bold-800 grey darken-2">@GlobalConfig.ProjectName</a>, All rights reserved.
            </span>
            <span class="float-md-right d-xs-block d-md-inline-block">
                Hand-crafted & Made with <i class="icon-heart5 pink"></i>
            </span>
        </p>
    </footer>

    @Scripts.Render("~/jQuery/core")
    @Scripts.Render("~/jQuery/ui")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $('img').attr('data-action', 'zoom');

        var status =@status;
        if(status==0){
            toastr.error('@message', 'Error !');
        }
        else if(status==1){
            toastr.success('@message', 'Success.');
        }
        else if(status==2){
            toastr.info('@message', 'Info.');
        }
        else if(status==3){
            toastr.warning('@message', 'Warning !');
        }
        else if(status==4){
            toastr.info('@message', 'Message.');
        }
    });
    </script>
</body>
</html>

Glaneir.Admin/Views/Users/Index.cshtml
@model IQueryable<UserDetailsModel>
@{
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

@helper ActionButtons(string Id, bool IsActive)
{
    <a href="javascript:;" class="btn btn-sm btn-primary btn-red deactivate" data-id="@Id" style="display:@(IsActive?"inline-block;":"none;")">
        <i class="icon-ban"></i> Deactivate
    </a>

    <a href="javascript:;" class="btn btn-sm btn-primary btn-green activate" data-id="@Id" style="display:@(!IsActive?"inline-block;":"none;")">
        <i class="icon-toggle-right"></i> Activate
    </a>

    <a href="@Url.Action("Delete", "Users", new { @id = Id })" class="btn btn-sm btn-primary btn-blue">
        <i class="icon-box"></i> Delete
    </a>

}

@helper NameLink(string UserId, long NumberOFCard)
{
    <a href="@Url.Action("ViewCardByUserId", "Card", new { @id = UserId })">
        @NumberOFCard
    </a>
}
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">All Users</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {

                               column.Add(p => p.Name)
                               .Titled("Full Name")
                               .Filterable(true)
                                .Sortable(true);

                               column.Add(p => p.Email)
                               .Titled("Email")
                               .Filterable(true);

                               column.Add(p => p.PhoneNumber)
                             .Titled("Phone Number")
                             .Filterable(true);

                               column.Add(P => P.NumberOFCard)
                            .Titled("Number Of card")
                            .Filterable(true)
                             .Sortable(true)
                            .Sanitized(false)
                            .Encoded(false)
                            .RenderValueAs(x => NameLink(x.UserId, x.NumberOFCard));

                               column.Add()
                            .Titled("Register Date")
                            .RenderValueAs(x => x.CreatedDate.ToString("dd/MM/yyyy"));

                               column.Add()
                               .Titled("Action")
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => ActionButtons(x.UserId, x.IsVerifyed));

                           }).Selectable(false).WithPaging(10)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {

    @Scripts.Render("~/jQuery/gridMvc")
    <script type="text/javascript">
        ActiveMenu("AllUsers");
         $(".jsgrid-grid-body").css('overflow-x', 'auto');

           $(function () {
               $(".deleteData").click(
                   function () {
                deleteRow($(this), '@Url.Action("Delete")');
            });
           });


           $(function () {
            $(".activate").click(function () {
                var control = $(this);
                var Url = '@Url.Action("ActiveToggle")';

                 swal({
                     title: "Are you sure to activate this user?",
                     //text: "You will not be able to recover this date!",
                     type: "warning",
                     showCancelButton: true,
                     confirmButtonColor: "#DA4453",
                     confirmButtonText: "Yes, activated it!",
                     cancelButtonText: "No, cancel plx!",
                     closeOnConfirm: false,
                     closeOnCancel: false
                 }, function (isConfirm) {
                     if (isConfirm) {
                         $.post(Url, { 'id': $(control).attr('data-id') }, function (response) {
                             if (response.Status == 1) {
                                 setTimeout(function () {
                                         control.parent().find(".deactivate").show()
                                         control.hide()
                                 }, 300);

                                 swal("Activated!", response.Message, "success");

                             }
                             else {
                                 control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-ban');
                                 swal("Error", response.Message, "error");
                             }
                         });
                     } else {
                         control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-ban');
                         swal("Cancelled", "Your record is safe :)", "info");
                     }
                 });
             });

            $(".deactivate").click(function () {
                 var control = $(this);
                 var Url = '@Url.Action("ActiveToggle")';

                 swal({
                     title: "Are you sure to deactivate this user?",
                     type: "warning",
                     showCancelButton: true,
                     confirmButtonColor: "#DA4453",
                     confirmButtonText: "Yes, deactivated it!",
                     cancelButtonText: "No, cancel plx!",
                     closeOnConfirm: false,
                     closeOnCancel: false
                 }, function (isConfirm) {
                     if (isConfirm) {
                         $.post(Url, { 'id': $(control).attr('data-id') }, function (response) {
                             if (response.Status == 1) {
                                 setTimeout(function () {
                                         control.parent().find(".activate").show()
                                         control.hide()
                                 }, 300);
                                 swal("Deactivated!", response.Message, "success");

                             }
                             else {
                                 control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-toggle-right');
                                 swal("Error", response.Message, "error");
                             }
                         });
                     } else {
                         control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-toggle-right');
                         swal("Cancelled", "Your record is safe :)", "info");
                     }
                 });
            });
        });
    </script>
}

Glaneir.Admin/Views/Utility/About.cshtml
@model UtilityModel
@{
    ViewBag.Title = "About Us";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/summernote")
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">About Us</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        @using (Html.BeginForm("AboutPost", "Utility", FormMethod.Post, new { @id = "frmTerms", @class = "form-horizontal" }))
                        {
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-11">
                                        @Html.TextAreaFor(x => x.Description)
                                        @Html.ValidationMessageFor(x => x.Description)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <input type="submit" class="btn btn-md btn-primary" value="Save" />
                                        <a href="@Url.Action("Index","Home")" class="btn btn-md btn-grey">
                                            Cancel
                                        </a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    @Scripts.Render("~/jQuery/summernote")

    <script type="text/javascript">
        ActiveMenu("About")
        $(function () {
            $('#Description').summernote({
                height: 200,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: false,
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                ],
            });
        });
    </script>
}